spring.application.name=WebIPMI

#################################################################################
# DATABASE ######################################################################
#################################################################################
spring.datasource.url=jdbc:h2:mem:webipmidb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS app_webipmi
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.h2.console.enabled=true

#################################################################################
# JPA ###########################################################################
#################################################################################
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=app_webipmi
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

#################################################################################
# ENVERS ########################################################################
#################################################################################
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_AUD
spring.jpa.properties.org.hibernate.envers.audit_table_prefix=
spring.jpa.properties.org.hibernate.envers.revision_field_name=REV_ID
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=REV_TYPE
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
